### ISSUE TITLE
Rust tuples have empty field names

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/lldb#21]
This will create problems for many, if not all, LLDB GUI's, because they'll probably expect distinct field names (VSCode does, for example).  
Underscore-prefixed field names aren't really that bad.   Dot-prefixed ones, that mimic Rust syntax, would be okay too.

**Comment by tromey** [comment]
How about just plain integers?  That seems more rust-like to me.

**Comment by vadimcn** [comment]
That'd be fine.

**Comment by tromey** [comment]
Seems like that push should have closed this.
