### ISSUE TITLE
lldb-preview "missing" in recent nightlies

### ISSUE THREAD

**Issue by dvdplm** [rust-lang/lldb#25]
There seems to be an issue with the nightly build since Nov 26. Not sure if this is a known issue or not.

**Comment by tromey** [comment]
Thanks for the report!  I appreciate it because, although I did notice that lldb was disabled this time, I imagine there will be other times where I miss it.  See https://github.com/rust-lang/rust/pull/56298.  I'm closing this as it is in progress already.
