### ISSUE TITLE
move to monorepo

### ISSUE THREAD

**Issue by jankratochvil** [rust-lang/lldb#33]
LLVM is going to merge all its repos to a single one, it would be easier to rebase the Rust branch on top of it:
> [lldb-dev] LLVM git monorepo mirror published
> https://lists.llvm.org/pipermail/lldb-dev/2019-January/014591.html

**Comment by cuviper** [comment]
We've already migrated -- see https://github.com/rust-lang/llvm-project

@alexcrichton perhaps we should archive all of the old repos? It would be nice to move the issues over though first.

**Comment by tromey** [comment]
@jankratochvil can you resubmit your patches against the monorepo?  Or at least whichever ones are required, since I thought @cuviper already fixed some of those things?  Feel free to "r?" me there, thanks.

**Comment by jankratochvil** [comment]
OK, https://github.com/rust-lang/llvm-project/tree/rustc/8.0-2019-01-16 seems to have already done all this merging stuff.  But then it would be nice if this github repo could mention https://github.com/rust-lang/llvm-project/tree/rustc/8.0-2019-01-16 is a more fresh branch of this code.

**Comment by tromey** [comment]
I tried to change the repository description but I can't get github to give me an edit button for it.  Works fine for my personal repositories though.

**Comment by jankratochvil** [comment]
I have edited local Wiki with the URL, I hoped it will be only submitted for approval but it seems to be changed now. Feel free to do whatever with it.
